name: Release build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          ./gradlew KeePassJava2-android:assembleRelease

      - name: Store APK file
        uses: actions/upload-artifact@v2
        with:
          name: KeePassJava2-android
          path: |
              ./KeePassJava2-android/build/outputs/aar/KeePassJava2-android-release.aar
